//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use sea_orm::IntoActiveValue;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "gender")]
pub enum Gender {
    #[sea_orm(string_value = "Male")]
    Male,
    #[sea_orm(string_value = "Female")]
    Female,
    #[sea_orm(string_value = "Intersex")]
    Intersex,
}

/// Convert `Gender` to `ActiveValue`
impl IntoActiveValue<Gender> for Gender {
    fn into_active_value(self) -> sea_orm::ActiveValue<Gender> {
        sea_orm::ActiveValue::Set(self)
    }
}
